Alterações dos modelos baseado no novo banco
Grupo02-Biopark/ambiente-saga pull request #56
Opened 2024-05-01 21:32 UTC by GusDechotti

2024-05-01 21:40 UTC, heloshartmann requested changes
Faltou o migration.

2024-05-02 01:50 UTC, GusDechotti commented
@heloshartmann alteração feita. Peço que por favor aprove.

2024-05-02 02:09 UTC, heloshartmann reviewed
@GusDechotti estou esperando o @devPisa responder, para ver se mantem a alteração na entidade resposta.

2024-05-02 12:20 UTC, heloshartmann requested changes
tirar o atributo estado de resposta

2024-05-02 21:29 UTC, GusDechotti commented
@heloshartmann alterações feitas

2024-05-02 21:54 UTC, heloshartmann requested changes
Alterar migrations, adicionar default.

2024-05-02 22:01 UTC, heloshartmann approved these changes

2024-05-02 22:02 UTC, merged